### ISSUE TITLE
fix SVG scaling

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/gui#32]
The new preprocessing is great but the SVG scaling with the viewbox seems broken again, at least in my case it does not fill its area and it does respond to zoom commands which it was immune to before.

**Comment by KonradHoeffner** [comment]
I'm investigating this now.

**Comment by Yagnap** [comment]
Me too, I fixed the regex so it correctly applies both viewbox, width 100% for the svg element and y=5 for the genericdefs, but it still doesn't seem to be working properly

**Comment by Yagnap** [comment]
Even when using the old svg file (commit 9aa6b41) it doesn't do anything (for me, anyways) - maybe it has to do with the javascript?

**Comment by Yagnap** [comment]
Changed nothing since my last comment, now it somehow suddenly works for me again.
