### ISSUE TITLE
SoftwareProduct zu ApplicationSystemTypeCitation direkter Pfad Tabelle enthält Application System Type Classified

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/gui#46]
SoftwareProduct zu ApplicationSystemTypeCitation direkter Pfad Tabelle enthält Application System Type Classified

**Comment by Yagnap** [comment]
Scheint ein Problem mit dem Löschen der Tabelle zu sein

**Comment by KonradHoeffner** [comment]
Anscheinend liegt das Problem beim event listener der auf dem Pfad registriert wird.
