### ISSUE TITLE
Dokumentation für End-User

### ISSUE THREAD

**Issue by Yagnap** [hitontology/gui#47]
Ein paar gute, ganz einfache Erklärungen, was man da machen kann/wie man Software beschreiben kann

**Comment by KonradHoeffner** [comment]
Software beschreiben geht ja noch gar nicht aber ich erweitere erstmal die Legende.

**Comment by KonradHoeffner** [comment]
Text von Prof. Winter:

HITO contains data on concepts that can be used to describe application software products (e.g., application system types, functions, roles, outcome criteria, …). You can find these concepts on the [diagram](https://urz365-my.sharepoint.com/:p:/g/personal/aw91powu_uni-leipzig_de/EWnmQnPg--lBoSNUrIviHAkBhxXdk7jJ1lQxj6fK_j0Fgw?e=X4UWfl). For a given concept, its datasets describe instances of this concept. For some concepts, such as "roles", different terms are available. There are colloquial terms ("folks's terms") and terms from terminologies ("terminology items"), which are also related to each other. In HITO, for example, the colloquial term "Laboratory Manager" has a classifying relationship with the term "Laboratory technician occupation". The term "Laboratory technician occupation" can be related to other colloquial terms. The term "Laboratory technician occupation" is taken from the terminology "SNOMED CT User Group Catalogue"; this terminology is an instance of the term "terminologies". 

Moreover, HITO contains further relationships between concepts, such as the relationship "evaluates" between the concepts "study" and "application software product". One instance of this relationship describes, for example, that the study entitled "The Influence that Electronic Prescribing ..." evalutes the application software product "Medicator". 

You may now have quite complex questions like the following: 

    What studies report on  

    the usage of application software product ASP? 

    application software products … 

    suitable for supporting work in organizational unit U?  

    suitable for supporting work of role R?  

    suitable for supporting information processing function IPF?  

    having feature F? 

    … 

    outcome criteria of outcome criteria catalog OCC? 

    What features are used when information processing function IPF shall be supported? 

    What features do application software products use for supporting information processing function IPF 

    For what application software products do we have information regarding their fulfilment of the outcome criterion OC   

    What application software products are suitable for implementing an application system of type AST? 

    … 

Such questions involve complex relationships between two concepts. Let's assume you need application software for a specific professional group in a hospital, i.e., a specific role R. Then you could ask the question, "what studies report on application software products suitable for supporting work of various roles?". This is about the relationship between the concepts "studies" and "roles". To find instances for this relationship first left-click to the concept "studies" in the diagram. If you are interested in colloquial terms for roles, you then right-click to the "folks' term" concept related to "roles"; if you are interested in terms from terminologies right-click to "terminologie items" nearby.  

In this case, HITO shows you two connection paths between the clicked concepts in different colors. Only paths are shown, for which there is data on instances of these paths in HITO. In our example, one of these paths includes the concept "application software products", the other does not. If you click e.g., the path via "application software products", a table with the instances of this path is displayed. In this case, the table contains, for example, the information that in the study "The Influence that Electronic Prescribing ..." the application software product "Medicator" was evaluated and that this product can be used by people with the role colloquially referred to as "Doctor". You can also see that "Doctor" was assigned to "Physician occupation" , an item of a terminology. If several rows are displayed in the results table, you can set filters in the table header to find the data you need.  

Just give it a try for some of the questions mentioned above. We hope you find HITO helpful.

**Comment by KonradHoeffner** [comment]
Auf Basis von Prof. Winters Vorschlag habe ich eine help.html entworfen.
@Yagnap: Bitte 1-2 Screenshots hinzufügen und prüfen, ob es eine Abweichung zwischen der Hilfe und dem Prototypen gibt. Wenn ja, prüfen ob wir es einfach implementieren können, ansonsten erstmal in der Hilfe anpassen.

**Comment by KonradHoeffner** [comment]
`&#129032; go back to search`: The unicode symbol isn't shown because it's not included in the font that is selected on my Linux/Gnome/Firefox system, which is NimbusRoman-Regular.

**Comment by KonradHoeffner** [comment]
The edges label in the table headers are now shown in passive form, we need a new screenshot there.

**Comment by KonradHoeffner** [comment]
Wait with new screenshot until new rework of table.
