### ISSUE TITLE
human readable long form table headers 

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/gui#50]
> Zur besseren Lesbarkeit der Ergebnistabellen sollten im Tabellenkopf zwischen den Begriffen auch die verwendeten Relationen zwischen den Begriffen angezeigt werden. Ich stelle mir das als einigermaßen lesbaren Satz vor. Dabei müsste je nach Reihenfolge der Begriffe die aktive oder passive (Rückwerts) Version der Relation verwendet werden.

**Comment by KonradHoeffner** [comment]
@AlfredWinter: Es sind jetzt erstmal die Kürzel der Relationen in der Tabelle, ausgeschriebene Form und Passivkonstruktionen folgen.

**Comment by AlfredWinter** [comment]
weiter so

**Comment by KonradHoeffner** [comment]
Hier ein Vorschlag von Google Gemini:

I apologize for the mistakes in the previous responses. Here's the table with only the "inverse" column labels modified, keeping all other information exactly the same as you provided:

| p | domain | range | label | inverse |
|---|---|---|---|---|
| [http://hitontology.eu/ontology/operatingSystem](http://hitontology.eu/ontology/operatingSystem) | Software Product | Operating System | operating system | **is provided by** |
| [http://hitontology.eu/ontology/language](http://hitontology.eu/ontology/language) | Software Product | Language | language | **is used in** |
| [http://hitontology.eu/ontology/astClaFrom](http://hitontology.eu/ontology/astClaFrom) | Application System Type Classified | Application System Type Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/evaluatesApplicationSystemType](http://hitontology.eu/ontology/evaluatesApplicationSystemType) | Study | Application System Type Citation | evaluates | **is evaluated by** |
| [http://hitontology.eu/ontology/implements](http://hitontology.eu/ontology/implements) | Software Product | Application System Type Citation | implements | **is implemented by** |
| [http://hitontology.eu/ontology/spIsOfAstCit](http://hitontology.eu/ontology/spIsOfAstCit) | Software Product | Application System Type Citation | is of | **is type of** |
| [http://hitontology.eu/ontology/astCitClassifiedAs](http://hitontology.eu/ontology/astCitClassifiedAs) | Application System Type Citation | Application System Type Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spIsOfAstCla](http://hitontology.eu/ontology/spIsOfAstCla) | Software Product | Application System Type Classified | is of | **is type of** |
| [http://hitontology.eu/ontology/catalogue](http://hitontology.eu/ontology/catalogue) | Classified | Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/citation](http://hitontology.eu/ontology/citation) | Software Product | Citation | citation | **is cited by** |
| [http://hitontology.eu/ontology/classified](http://hitontology.eu/ontology/classified) | Citation | Classified | classified as | **is a classification of** |
| [http://hitontology.eu/ontology/subClassifiedOf](http://hitontology.eu/ontology/subClassifiedOf) | Classified | Classified | subclassified of | **superclassified of** |
| [http://hitontology.eu/ontology/client](http://hitontology.eu/ontology/client) | Software Product | Client | client | **is served by** |
| [http://hitontology.eu/ontology/databaseManagementSystem](http://hitontology.eu/ontology/databaseManagementSystem) | Software Product | Database Management System | database management system |  |
| [http://hitontology.eu/ontology/efClaFrom](http://hitontology.eu/ontology/efClaFrom) | Enterprise Function Classified | Function Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/spSupportsEfCit](http://hitontology.eu/ontology/spSupportsEfCit) | Software Product | Enterprise Function Citation | supports | **is supported by** |
| [http://hitontology.eu/ontology/supportsFunction](http://hitontology.eu/ontology/supportsFunction) | Feature Citation | Enterprise Function Citation | supports function citation |  |
| [http://hitontology.eu/ontology/astClaSupportsEfCla](http://hitontology.eu/ontology/astClaSupportsEfCla) | Application System Type Classified | Enterprise Function Classified | supports | **is supported by** |
| [http://hitontology.eu/ontology/efCitClassifiedAs](http://hitontology.eu/ontology/efCitClassifiedAs) | Enterprise Function Citation | Enterprise Function Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spSupportsEfCla](http://hitontology.eu/ontology/spSupportsEfCla) | Software Product | Enterprise Function Classified | supports | **is supported by** |
| [http://hitontology.eu/ontology/subFunctionOf](http://hitontology.eu/ontology/subFunctionOf) | Enterprise Function Classified | Enterprise Function Classified | subfunction of | **superfunction of** |
| [http://hitontology.eu/ontology/supportsFunctionClassified](http://hitontology.eu/ontology/supportsFunctionClassified) | Feature Classified | Enterprise Function Classified | supports classified function |  |
| [http://hitontology.eu/ontology/fClaFrom](http://hitontology.eu/ontology/fClaFrom) | Feature Classified | Feature Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingFeature](http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingFeature) | Study | Feature Citation | evaluates | **is evaluated by (with a specific feature)** |
| [http://hitontology.eu/ontology/spOffersFCit](http://hitontology.eu/ontology/spOffersFCit) | Software Product | Feature Citation | offers | **is offered by** |
| [http://hitontology.eu/ontology/supportedByFeatureCitation](http://hitontology.eu/ontology/supportedByFeatureCitation) | Enterprise Function Citation | Feature Citation | supported by feature citation |  |
| [http://hitontology.eu/ontology/fCitClassifiedAs](http://hitontology.eu/ontology/fCitClassifiedAs) | Feature Citation | Feature Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spOffersFCla](http://hitontology.eu/ontology/spOffersFCla) | Software Product | Feature Classified | offers | **is offered by** |
| [http://hitontology.eu/ontology/subFeatureOf](http://hitontology.eu/ontology/subFeatureOf) | Feature Classified | Feature Classified | subfeature of | **superfeature of** |
| [http://hitontology.eu/ontology/interoperability](http://hitontology.eu/ontology/interoperability) | Software Product | Interoperability Standard | interoperability | **is interoperable with** |
| [http://hitontology.eu/ontology/subInteroperabilityOf](http://hitontology.eu/ontology/subInteroperabilityOf) | Interoperability Standard | Interoperability Standard | subinteroperability of | **superinteroperates with** |
| [http://hitontology.eu/ontology/publishedInJournal](http://hitontology.eu/ontology/publishedInJournal) | Study | Journal | published In Journal | **is published in** |
| http

**Comment by KonradHoeffner** [comment]
Manuelle Korrektur der fragwürdigen Gemini-Vorschläge:

Hier ein Vorschlag von Google Gemini:

| p | domain | range | label | inverse |
|---|---|---|---|---|
| [http://hitontology.eu/ontology/operatingSystem](http://hitontology.eu/ontology/operatingSystem) | Software Product | Operating System | operating system | is operating system of  |
| [http://hitontology.eu/ontology/language](http://hitontology.eu/ontology/language) | Software Product | Language | language |is language of |
| [http://hitontology.eu/ontology/astClaFrom](http://hitontology.eu/ontology/astClaFrom) | Application System Type Classified | Application System Type Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/evaluatesApplicationSystemType](http://hitontology.eu/ontology/evaluatesApplicationSystemType) | Study | Application System Type Citation | evaluates | **is evaluated by** |
| [http://hitontology.eu/ontology/implements](http://hitontology.eu/ontology/implements) | Software Product | Application System Type Citation | implements | **is implemented by** |
| [http://hitontology.eu/ontology/spIsOfAstCit](http://hitontology.eu/ontology/spIsOfAstCit) | Software Product | Application System Type Citation | is of | **is type of** |
| [http://hitontology.eu/ontology/astCitClassifiedAs](http://hitontology.eu/ontology/astCitClassifiedAs) | Application System Type Citation | Application System Type Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spIsOfAstCla](http://hitontology.eu/ontology/spIsOfAstCla) | Software Product | Application System Type Classified | is of | **is type of** |
| [http://hitontology.eu/ontology/catalogue](http://hitontology.eu/ontology/catalogue) | Classified | Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/citation](http://hitontology.eu/ontology/citation) | Software Product | Citation | citation | **is cited by** |
| [http://hitontology.eu/ontology/classified](http://hitontology.eu/ontology/classified) | Citation | Classified | classified as | **is a classification of** |
| [http://hitontology.eu/ontology/subClassifiedOf](http://hitontology.eu/ontology/subClassifiedOf) | Classified | Classified | subclassified of | **superclassified of** |
| [http://hitontology.eu/ontology/client](http://hitontology.eu/ontology/client) | Software Product | Client | client | is client of |
| [http://hitontology.eu/ontology/databaseManagementSystem](http://hitontology.eu/ontology/databaseManagementSystem) | Software Product | Database Management System | database management system | is used in |
| [http://hitontology.eu/ontology/efClaFrom](http://hitontology.eu/ontology/efClaFrom) | Enterprise Function Classified | Function Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/spSupportsEfCit](http://hitontology.eu/ontology/spSupportsEfCit) | Software Product | Enterprise Function Citation | supports | **is supported by** |
| [http://hitontology.eu/ontology/supportsFunction](http://hitontology.eu/ontology/supportsFunction) | Feature Citation | Enterprise Function Citation | supports function citation | is supported by |
| [http://hitontology.eu/ontology/astClaSupportsEfCla](http://hitontology.eu/ontology/astClaSupportsEfCla) | Application System Type Classified | Enterprise Function Classified | supports | **is supported by** |
| [http://hitontology.eu/ontology/efCitClassifiedAs](http://hitontology.eu/ontology/efCitClassifiedAs) | Enterprise Function Citation | Enterprise Function Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spSupportsEfCla](http://hitontology.eu/ontology/spSupportsEfCla) | Software Product | Enterprise Function Classified | supports | **is supported by** |
| [http://hitontology.eu/ontology/subFunctionOf](http://hitontology.eu/ontology/subFunctionOf) | Enterprise Function Classified | Enterprise Function Classified | subfunction of | **superfunction of** |
| [http://hitontology.eu/ontology/supportsFunctionClassified](http://hitontology.eu/ontology/supportsFunctionClassified) | Feature Classified | Enterprise Function Classified | supports classified function |  |
| [http://hitontology.eu/ontology/fClaFrom](http://hitontology.eu/ontology/fClaFrom) | Feature Classified | Feature Catalogue | from catalogue | **contains** |
| [http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingFeature](http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingFeature) | Study | Feature Citation | evaluates | **is evaluated by |
| [http://hitontology.eu/ontology/spOffersFCit](http://hitontology.eu/ontology/spOffersFCit) | Software Product | Feature Citation | offers | **is offered by** |
| [http://hitontology.eu/ontology/supportedByFeatureCitation](http://hitontology.eu/ontology/supportedByFeatureCitation) | Enterprise Function Citation | Feature Citation | supported by feature citation | supports  |
| [http://hitontology.eu/ontology/fCitClassifiedAs](http://hitontology.eu/ontology/fCitClassifiedAs) | Feature Citation | Feature Classified | classified as | **classifies** |
| [http://hitontology.eu/ontology/spOffersFCla](http://hitontology.eu/ontology/spOffersFCla) | Software Product | Feature Classified | offers | **is offered by** |
| [http://hitontology.eu/ontology/subFeatureOf](http://hitontology.eu/ontology/subFeatureOf) | Feature Classified | Feature Classified | subfeature of | **superfeature of** |
| [http://hitontology.eu/ontology/interoperability](http://hitontology.eu/ontology/interoperability) | Software Product | Interoperability Standard | interoperability | **is interoperability of** |
| [http://hitontology.eu/ontology/subInteroperabilityOf](http://hitontology.eu/ontology/subInteroperabilityOf) | Interoperability Standard | Interoperability Standard | subinteroperability of | **superinteroperability of  ** |
| [http://hitontology.eu/ontology/publishedInJournal](http://hitontology.eu/ontology/publishedInJournal) | Study | Journal | published In Journal | published |

**Comment by AlfredWinter** [comment]
Was hat Gemini hierbei gemacht??

**Comment by AlfredWinter** [comment]
Passiv ist besser. Nun habe ich die Gemini-Aktion verstanden. 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter, FIAHSI
Tel.:      +49 341-97-16107, 
Mobil: +49 151 550 19 248
E-Mail: ***@***.*** 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedInfoL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. Eva Inés Obergfell, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner ***@***.***> 
Gesendet: Mittwoch, 17. April 2024 09:13
An: hitontology/gui ***@***.***>
Cc: AlfredWinter ***@***.***>; Mention ***@***.***>
Betreff: [Extern] Re: [hitontology/gui] human readable long form table headers (Issue #50)
 
Screenshot.from.2024-04-17.09-00-14.png (view on web)
@AlfredWinter:
Es werden jetzt die Labels statt der IDs angezeigt.
Anstelle von grammatischen Passivkonstruktionen habe ich Richtungspfeile verwendet.
Ist das so OK für Sie oder hätten Sie doch lieber Passivkonstruktionen?
Dann brauchen wir eine Passivform für jede Property, unten schon ein paar Vorschläge.
 p
 domain
 range
 label
 inverse
 http://hitontology.eu/ontology/operatingSystem
 Software Product
 Operating System
 operating system
  is operating system of
 http://hitontology.eu/ontology/language
 Software Product
 Language
 language
  is language of
 http://hitontology.eu/ontology/astClaFrom
 Application System Type Classified
 Application System Type Catalogue
 from catalogue
 contains 
 http://hitontology.eu/ontology/evaluatesApplicationSystemType
 Study
 Application System Type Citation
 evaluates
 is evaluated by
 http://hitontology.eu/ontology/implements
 Software Product
 Application System Type Citation
 implements
 is implemented by
 http://hitontology.eu/ontology/spIsOfAstCit
 Software Product
 Application System Type Citation
 is of
  is type of (?, klingt genauso wie "is of")
 http://hitontology.eu/ontology/astCitClassifiedAs
 Application System Type Citation
 Application System Type Classified
 classified as
  classifies(?)
 http://hitontology.eu/ontology/spIsOfAstCla
 Software Product
 Application System Type Classified
 is of
  is type of
 http://hitontology.eu/ontology/catalogue
 Classified
 Catalogue
 from catalogue
  contains
 http://hitontology.eu/ontology/citation
 Software Product
 Citation
 citation
  is citation of
 http://hitontology.eu/ontology/classified
 Citation
 Classified
 classified as
  
 http://hitontology.eu/ontology/subClassifiedOf
 Classified
 Classified
 subclassified of
  superclassified of
 http://hitontology.eu/ontology/client
 Software Product
 Client
 client
  is client of
 http://hitontology.eu/ontology/databaseManagementSystem
 Software Product
 Database Management System
 database management system
  
 http://hitontology.eu/ontology/efClaFrom
 Enterprise Function Classified
 Function Catalogue
 from catalogue
  
 http://hitontology.eu/ontology/spSupportsEfCit
 Software Product
 Enterprise Function Citation
 supports
  
 http://hitontology.eu/ontology/supportsFunction
 Feature Citation
 Enterprise Function Citation
 supports function citation
  
 http://hitontology.eu/ontology/astClaSupportsEfCla
 Application System Type Classified
 Enterprise Function Classified
 supports
  
 http://hitontology.eu/ontology/efCitClassifiedAs
 Enterprise Function Citation
 Enterprise Function Classified
 classified as
  
 http://hitontology.eu/ontology/spSupportsEfCla
 Software Product
 Enterprise Function Classified
 supports
  
 http://hitontology.eu/ontology/subFunctionOf
 Enterprise Function Classified
 Enterprise Function Classified
 subfunction of
  
 http://hitontology.eu/ontology/supportsFunctionClassified
 Feature Classified
 Enterprise Function Classified
 supports classified function
  
 http://hitontology.eu/ontology/fClaFrom
 Feature Classified
 Feature Catalogue
 from catalogue
  
 http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingFeature
 Study
 Feature Citation
 evaluates
  
 http://hitontology.eu/ontology/spOffersFCit
 Software Product
 Feature Citation
 offers
  
 http://hitontology.eu/ontology/supportedByFeatureCitation
 Enterprise Function Citation
 Feature Citation
 supported by feature citation
  
 http://hitontology.eu/ontology/fCitClassifiedAs
 Feature Citation
 Feature Classified
 classified as
  
 http://hitontology.eu/ontology/spOffersFCla
 Software Product
 Feature Classified
 offers
  
 http://hitontology.eu/ontology/subFeatureOf
 Feature Classified
 Feature Classified
 subfeature of
  
 http://hitontology.eu/ontology/interoperability
 Software Product
 Interoperability Standard
 interoperability
  
 http://hitontology.eu/ontology/subInteroperabilityOf
 Interoperability Standard
 Interoperability Standard
 subinteroperability of
  
 http://hitontology.eu/ontology/publishedInJournal
 Study
 Journal
 published In Journal
  
 http://hitontology.eu/ontology/ouClaFrom
 Organizational Unit Classified
 Organizational Unit Catalogue
 from catalogue
  
 http://hitontology.eu/ontology/evaluatesApplicationSystemTypeUsedInUnit
 Study
 Organizational Unit Citation
 evaluates application system or software product used in
  
 http://hitontology.eu/ontology/spUsedInOuCit
 Software Product
 Organizational Unit Citation
 used in
  
 http://hitontology.eu/ontology/ouCitClassifiedAs
 Organizational Unit Citation
 Organizational Unit Classified
 classified as
  
 http://hitontology.eu/ontology/spUsedInOuCla
 Software Product
 Organizational Unit Classified
 used in
  
 http://hitontology.eu/ontology/ocEvaluatesOcCit
 Study
 Outcome Criteria Citation
 evaluates
  
 http://hitontology.eu/ontology/ocCitClassifiedAs
 Outcome Criteria Citation
 Outcome Criteria Classified
 classified as
  
 http://hitontology.eu/ontology/programmingLibrary
 Software Product
 Programming Library
 programming library or toolkit
  
 http://hitontology.eu/ontology/evaluatesProduct
 Study
 Software Product
 evaluates
  
 http://hitontology.eu/ontology/softwareProductComponent
 Software Product
 Software Product
 software product component
  
 http://hitontology.eu/ontology/studyMethod
 Study
 Study Method
 study method
  
 http://hitontology.eu/ontology/userClaFrom
 User Group Classified
 User Group Catalogue
 from catalogue
  
 http://hitontology.eu/ontology/evaluatesApplicationSystemTypeHavingUserGroup
 Study
 User Group Citation
 evaluates application system or software product used by
  
 http://hitontology.eu/ontology/spUsedByUserCit
 Software Product
 User Group Citation
 offers
  
 http://hitontology.eu/ontology/spUsedByUserCla
 Software Product
 User Group Classified
 used by
  
 http://hitontology.eu/ontology/userCitClassifiedAs
 User Group Citation
 User Group Classified
 classified as
  
Für später: Generiert mit select distinct ?p STR(?domain) STR(?range) STR(?l) ?inverse {{?p a owl:ObjectProperty.} UNION {?p a owl:DatatypeProperty.} ?p rdfs:label ?l. ?p rdfs:domain/rdfs:label ?domain. ?p rdfs:range/rdfs:label ?range. BIND("" AS ?inverse).}

**Comment by KonradHoeffner** [comment]
OK, ich baue es ein!
