### ISSUE TITLE
Gestaltungsvorschlag AW

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/gui#51]
![Slide1](https://github.com/hitontology/gui/assets/839577/573d7a70-912f-4999-87bb-5cfd1c692182)

**Comment by KonradHoeffner** [comment]
Das sieht auf jeden Fall übersichtlicher aus, weicht aber ja vom Diagramm ab.
Soll das HITO-Diagramm auch dahingehend angepasst werden, dass die beiden wieder synchron sind oder haben wir dann zwei verschiedene Versionen?
In letzterem Fall können wir das auch im Programm anpassen, damit wir weiter von der momentanen Methode profitieren, im Fall eines Diagramm-Updates dies immer gleich nutzen zu können.

Und die Sprechblasen, können das Popups sein die bei Mouseover erscheinen oder sollen die beim Start alle gleichzeitig eingeblendet werden?

**Comment by KonradHoeffner** [comment]
* [ ] use HITO definitions (maybe revise later)
* [ ] bubbles as mouseovers

**Comment by KonradHoeffner** [comment]
- [ ] function -> enterprise function

**Comment by Yagnap** [comment]
Bubbles as mouseovers: Use as description in yEd, then click "export description as tooltip checkbox" when exporting as SVG

**Comment by KonradHoeffner** [comment]
@Yagnap: Mouseovers are now in the redesign branch. The definitions are queried from the HITO SPARQL endpoint and added as SVG title tags in commit https://github.com/hitontology/gui/commit/ac436d1ad7e3b55148e43aea4e20ffbb563dfcac.
