### ISSUE TITLE
Make filtering the table possible

### ISSUE THREAD

**Issue by Yagnap** [hitontology/gui#52]
e.g. by textfield in table header/writing or like in  [this](https://user-images.githubusercontent.com/43496783/122712136-b8442100-d263-11eb-9e2a-c3414e17db92.png) image (in the graph directly) or both

as described in the help.html

**Comment by KonradHoeffner** [comment]
Filtering is already covered by the native AG Grid functionality.
The right side of each column header has a "hamburger menu" that opens the filter box.
![Screenshot from 2024-04-19 11-07-35](https://github.com/hitontology/gui/assets/839577/aa53d294-e2c0-4822-afb1-6c374047d397)

Does this resolve the issue?
If this is not intuitive enough, please describe this in help.html maybe even with a screenshot but I would really prefer to not implement our own filter function when AG Grid already has such a nice one out of the box.

**Comment by KonradHoeffner** [comment]
Approved by Prof. Winter.
