### ISSUE TITLE
Make group boxes more visible

### ISSUE THREAD

**Issue by Yagnap** [hitontology/gui#64]
subtle grey background to make it more visible

**Comment by KonradHoeffner** [comment]
On my monitor, rgb(250,250,250) is hard to distinguish from white (it is a VA panel with bad color accuracy though), so I settled for rgb(248,248,248) for now, hope that is subtle enough and still visible enough.

**Comment by KonradHoeffner** [comment]
Oh and there is a massive diff in the SVG because I had to draw the group boxes at the beginning. Before they were drawn at the end so the background would cover the rest.
